#!/bin/bash


#!/bin/bash
# flag variables
u_flag=0
k_value="0"

# Parse command-line options using getopts
while getopts "k:u" opt; do
  case "$opt" in
    u)
      u_flag=1
      ;;
    k)
      k_value="$OPTARG"
      ;;
    *)
      usage
      ;;
  esac
done

# convert k value to str
k=$((k_value))


# Check if we need to perform additional actions
if [[ $u_flag -eq 1 ]]; then
  str="ACDEFGHIJKLMNOPQRSTUVWXYZ"
  char="${str:k:1}"
  char2="${str:k-1%25:1}"
  trans="[${char}-ZA-${char2}]"
  cat | tr '[A-Z]' $trans
else
  str="abcdefghijklmnopqrstuvwxyz"
  char="${str:k:1}"
  char2="${str:k-1%25:1}"
  trans="[${char}-za-${char2}]"
  cat | tr '[a-z]' $trans
fi

