#!/bin/bash

new="$(cat pb.txt | grep "$1")"

IFS=',' read -r -a arr <<< "$new"

# If the first argument is an integer
if [[ $1 =~ ^[+-]?[0-9]+$ ]]; then
  # Loop through the array and display "int" for each element
  for i in "${!arr[@]}"; do
    echo "int"
  done
else
  # If it's not an integer, just echo the string
  echo "$new"

  # Loop through the array and print numbers if they match the regex
  for i in "${!arr[@]}"; do
    if [[ ${arr[$i]} =~ ^[+-]?[0-9]+$ ]]; then
      echo "${arr[$i]}"
    fi
  done
fi
