#!/bin/bash
#!/bin/bash

str="ABCDEFGHIJKLMNOPQRSTUVWXYZ"

strpos="25"
position=$((strpos))


# Get the character at the specified position (1-based index)

# convert character to string 
char="${str:position:1}"
char2="${str:position-1%25:1}"

# insert character to tr parameter format
trans="[${char}-ZA-${char2}]"

echo $trans

# return


# echo "ABCDEFGHIJKLMNOPQRSTUVWXYZ" | tr '[A-Z]' $trans
