#!/bin/bash


#!/bin/bash
# flag variables
u_flag=0
k_value="0"

# Parse command-line options using getopts
while getopts "k:u" opt; do
  case "$opt" in
    u)
      u_flag=1
      ;;
    k)
      k_value="$OPTARG"
      ;;
    *)
      usage
      ;;
  esac
done



# convert k value to str
k=$((k_value))


# Check if we need to perform additional actions
if [[ $u_flag -eq 1 ]]; then
  trans=$(./create_pattern -k $k -u)
  cat | tr '[A-Z]' $trans
else
    trans=$(./create_pattern -k $k)
  cat | tr '[a-z]' $trans
fi

